CREATE DATABASE IF NOT EXISTS creditos;
USE creditos;

CREATE TABLE IF NOT EXISTS solicitudes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    correo VARCHAR(255) NOT NULL,
    dui VARCHAR(10) NOT NULL,
    monto DECIMAL(10,2) NOT NULL,
    tasa DECIMAL(5,2) NOT NULL,
    plazo INT NOT NULL,
    cuota DECIMAL(10,2) NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
